<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLeaguesTable extends Migration
{
    const TABLE_NAME = 'leagues';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(static::TABLE_NAME, function (Blueprint $table) {
            $table->uuid('league_id')->primary();
            $table->string('name', 255)->nullable();
            $table->uuid('organization_id')->nullable();
            $table->uuid('sport_id')->nullable();
            $table->string('slack_channel_id')->nullable();
            $table->timestamps();
            $table->softDeletes();


            $table->foreign('sport_id')->references('sport_id')->on('sports')->onDelete('set null')->onUpdate('CASCADE');
            $table->foreign('organization_id')->references('organization_id')->on('organizations')->onDelete('set null')->onUpdate('CASCADE');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists(static::TABLE_NAME);
    }
}
