<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMatchesTable extends Migration
{
    const TABLE_NAME = 'matches';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(static::TABLE_NAME, function (Blueprint $table) {
            $table->uuid('match_id')->primary();
            $table->uuid('league_id');
            $table->integer('team_1_score')->nullable()->default(0);
            $table->integer('team_2_score')->nullable()->default(0);
            $table->integer('team_1_penalties')->nullable()->default(0);
            $table->integer('team_2_penalties')->nullable()->default(0);
            $table->string('name')->nullable();
            $table->float('higher_score')->nullable()->default(0);
            $table->float('lower_score')->nullable()->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('league_id', 'league_fk')->references('league_id')->on('leagues')->onDelete('CASCADE
')->onUpdate('CASCADE');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists(static::TABLE_NAME);
    }
}
